name: Publish to NPM

env:
  NODE_VERSION: 19 # update to match .nvmrc
  PNPM_VERSION: 7

on:
  push:
    branches:
      - master
    paths:
      - package.json

jobs:
  build-test-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: "https://registry.npmjs.org"

      - uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Get release tag from package.json
        run: |
          echo "PACKAGE_VERSION=$(node -p "/^\d(?:\.\d)*\-([\w\-]+)[\.\+]?.*$/.exec(require('./package.json').version)?.[1] ?? 'latest'")" >> $GITHUB_ENV
          echo $PACKAGE_VERSION

      - name: Run tests
        run: pnpm test

      - name: Create git tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag $PACKAGE_VERSION
          git push --tags

      - name: Publish to NPM
        run: pnpm publish --access public --tag $PACKAGE_VERSION
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
