name: Bump pre-release version

env:
  NODE_VERSION: 19
  PNPM_VERSION: 7

on:
  workflow_dispatch:
    inputs:
      preid:
        description: "Prerelease ID"
        required: true
        default: "alpha"
        type: choice
        options:
          - alpha
          - beta
          - rc

jobs:
  chore-bump-version:
    name: Chore - bump version 🚀
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: "https://registry.npmjs.org"

      - uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          fetch-depth: 2

      - run: pnpm version --preid ${{ github.event.inputs.preid }} --git-tag-version=false prerelease

      - id: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          git commit -am "chore: ${PACKAGE_VERSION} pre-release"

      - run: git push
