name: Run npm version and push tags

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      version:
        description: New version semver
        required: true
        type: string
      tag:
        description: NPM tag
        required: false
        type: string
        default: "latest"

jobs:
  npm-version:
    uses: Tymek/npm-automation/.github/workflows/template.yml@main
    with:
      version: ${{ github.event.inputs.version }}
      tag: ${{ github.event.inputs.tag }}
    secrets:
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
