name: NPM & GitHub Release

env:
  NODE_VERSION: 19 # update to match .nvmrc
  PNPM_VERSION: 7

on:
  push:
    branches:
      - master
    paths:
      - package.json

jobs:
  build-test-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: "https://registry.npmjs.org"

      - uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Get version from package.json
        run: |
          echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
          echo "PACKAGE_TAG=$(node -p "/^\d(?:\.\d)*\-([\w\-]+)[\.\+]?.*$/.exec(require('./package.json').version)?.[1] ?? 'latest'")" >> $GITHUB_ENV
          echo $PACKAGE_VERSION
          echo $PACKAGE_TAG

      - name: Run tests
        run: pnpm test

      - name: Create git tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag v$PACKAGE_VERSION
          git push --tags

      - name: Publish to NPM
        run: pnpm publish --access public --tag $PACKAGE_TAG
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish GitHub Release
        run: |
          curl -L --fail \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GH_ACCESS_TOKEN}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${GITHUB_ACTION_REPOSITORY}/releases" \
            -d '{"tag_name":"v'$PACKAGE_VERSION'","name":"v'$PACKAGE_VERSION'","prerelease":'$([[ "$PACKAGE_TAG" == "latest" ]] && echo "false" || echo "true")',"generate_release_notes":true}'
