name: 🚀 Release LIB

on:
  workflow_dispatch:
    inputs:
      version:
        description: New version semver
        required: true
        type: string
      tag:
        description: NPM tag
        required: false
        type: string
        default: "latest"

jobs:
  from-template:
    uses: .github/workflows/template.yml@main
    with:
      version: ${{ github.event.inputs.version }}
      tag: ${{ github.event.inputs.tag }}
      directory: "./lib"
      working-directory: ./lib
    secrets:
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
